name: data_faker
description: A dart library for generating a fake data. This library make your life easier, also it's very customizable.
version: 0.0.5
homepage: https://github.com/elbeicktalat/data_faker

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  test: ^1.16.0
