name: data_faker
description: A dart library for generating a fake data.
version: 0.0.1
homepage: https://github.com/elbeicktalat/data_faker

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  test: ^1.16.0
